spring.application.name=Stock_Predictor

# Database (Supabase)
spring.datasource.url=jdbc:postgresql://db.idzkricnzzdpvcbzxayh.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Januarsechsundzwanzig2000!

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Alpha Vantage
alphavantage.api.key=6U06P1I29IBTB6L4

# CORS (Next.js dev server)
frontend.url=http://localhost:3000